config/routes.rb
Rails.application.routes.draw do
  # homes
  root to: 'homes#top'
  get 'homes/about'
  get 'homes/help'
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # user
  get '/confirm' => 'users#confirm', as: 'users_confirm'
  put '/users/:id/leave' => 'users#leave', as: 'users_leave'
  get '/users' => 'users#error' # hidden_field使用に伴うルーティングエラー用(新規登録)
  resources :users, only: %i[show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notices, only: [:index]
    delete '/notices/destroy_all' => 'notices#destroy_all'
  end
  # chat
  resources :chats, only: %i[show create]
  get '/chats' => 'chats#error' # hidden_field使用に伴うルーティングエラー用（チャット）
  # event
  patch 'events/:id/cancel' => 'events#cancel', as: 'cancel_event'
  resources :events, except: [:destroy] do
    get 'join' => 'events#join', as: 'join'
    delete 'leave' => 'events#leave', as: 'leave'
    resources :event_comments, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # group
  resources :groups, except: [:destroy] do
    get 'join' => 'groups#join', as: 'join'
    delete 'leave' => 'groups#leave', as: 'leave'
    resources :applies, only: %i[create destroy index]
    resources :group_news, only: %i[new create edit update destroy]
    resources :group_comments, only: %i[create destroy]
  end
  # search
  get 'searches/event' => 'searches#event'
  get 'searches/group' => 'searches#group'
  get 'searches/user' => 'searches#user'
  # tag
  resources :tags, only: [:show]
  # genre
  resources :genres, only: [:show]
  # contact
  resources :contacts, only: %i[new create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_user!

  def index
    # current_userのイベントに紐づいた通知一覧
    @event_notices = current_user.passive_event_notifications
    # @event_noticesの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @event_notices.where(is_checked: false).each do |notice|
      notice.update_attributes(is_checked: true)
    end
    # current_userのグループに紐づいた通知一覧
    @group_notices = current_user.passive_group_notifications
    # @event_noticesの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @group_notices.where(is_checked: false).each do |notice|
      notice.update_attributes(is_checked: true)
    end
  end

  # 通知を全削除
  def destroy_all
    @event_notices = current_user.passive_event_notifications.destroy_all
    @group_notices = current_user.passive_group_notifications.destroy_all
    redirect_to user_notices_path
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
  # 通知が発生しているか判定
  def unchecked_notifications
    @notifications = []
    @notifications = current_user.passive_event_notifications.where(is_checked: false) # イベント側の通知があれば@notificationsに格納
    @notifications += current_user.passive_group_notifications.where(is_checked: false) # グループ側の通知があれば@notificationsに追加
  end
end

app/views/notices/_event_notice.html.erb
<div>
  <% event_notices.each do |notice| %>
    <div class="border-bottom mb-2">
      <% if notice.action == "comment" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんが<%= link_to notice.event.name, event_path(notice.event) %>にコメントしました。</p>
      <% elsif notice.action == "follow" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんからフォローされました。</p>
      <% elsif notice.action == "join" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんが<%= link_to notice.event.name, event_path(notice.event) %>に参加しました。</p>
      <% elsif notice.action == "chat" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんからメッセージが届いています。</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/notices/_group_notice.html.erb
<div>
  <% group_notices.each do |notice| %>
    <div class="border-bottom mb-2">
      <% if notice.action == "comment" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんが<%= link_to notice.group.name, group_path(notice.group) %>にコメントしました。</p>
      <% elsif notice.action == "apply" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.visiter.name, user_path(notice.visiter) %>さんから、<%= link_to notice.group.name, group_path(notice.group) %>への参加申請がありました。</p>
      <% elsif notice.action == "approval" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.group.name, group_path(notice.group) %>への参加申請が許可されました。</p>
      <% elsif notice.action == "news" %>
        <p><i class="fas fa-exclamation-circle"></i> <%= link_to notice.group.name, group_path(notice.group) %>にお知らせが投稿されました。</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/notices/index.html.erb
<section id="notice" class="bg-light">
  <div class="container">
    <div class="row">
      <h3 class="text-center col-12 mt-3">通知</h3>
      <%= link_to user_notices_destroy_all_path, method: :delete, class:"col-6" do %>
        <i class="fas fa-trash" style="color: black;"></i>
        <h7 style="color: black;">全削除</h7>
      <% end %>
      <% if @event_notices.exists? %>
        <h3 class="text-center col-12 mt-3">イベント関連通知</h3>
        <div class="col-10">
          <%= render 'event_notice', event_notices: @event_notices %>
        </div>
      <% elsif @group_notices.exists? %>
        <h3 class="text-center col-12 mt-3">グループ関連通知</h3>
        <div class="col-10">
          <%= render 'group_notice', group_notices: @group_notices %>
        </div>
      <% else %>
        <p>通知はありません</p>
      <% end %>
    </div>
  </div>
</section>