config/routes.rb
Rails.application.routes.draw do
  # homes
  root to: 'homes#top'
  get 'homes/about'
  get 'homes/help'
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # user
  get '/confirm' => 'users#confirm', as: 'users_confirm'
  put '/users/:id/leave' => 'users#leave', as: 'users_leave'
  get '/users' => 'users#error' # hidden_field使用に伴うルーティングエラー用(新規登録)
  resources :users, only: %i[show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notices, only: [:index]
    delete '/notices/destroy_all' => 'notices#destroy_all'
  end
  # chat
  resources :chats, only: %i[show create]
  get '/chats' => 'chats#error' # hidden_field使用に伴うルーティングエラー用（チャット）
  # event
  patch 'events/:id/cancel' => 'events#cancel', as: 'cancel_event'
  resources :events, except: [:destroy] do
    get 'join' => 'events#join', as: 'join'
    delete 'leave' => 'events#leave', as: 'leave'
    resources :event_comments, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # group
  resources :groups, except: [:destroy] do
    get 'join' => 'groups#join', as: 'join'
    delete 'leave' => 'groups#leave', as: 'leave'
    resources :applies, only: %i[create destroy index]
    resources :group_news, only: %i[new create edit update destroy]
    resources :group_comments, only: %i[create destroy]
  end
  # search
  get 'searches/event' => 'searches#event'
  get 'searches/group' => 'searches#group'
  get 'searches/user' => 'searches#user'
  # tag
  resources :tags, only: [:show]
  # genre
  resources :genres, only: [:show]
  # contact
  resources :contacts, only: %i[new create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/group.rb
class Group < ApplicationRecord
  # バリデーション
  validates :name, length: { minimum: 1, maximum: 50 }, uniqueness: true
  validates :introduction, presence: true

  # アソシエーション
  has_many :group_users
  has_many :users, through: :group_users
  # 参加申請機能用
  has_many :applies, dependent: :destroy
  # 新着情報機能用
  belongs_to :group_new, optional: true
  # コメント機能用
  has_many :group_comments, dependent: :destroy
  # イベントとの紐づけ用
  has_many :events
  # 通知機能用
  has_many :group_notices, dependent: :destroy

  # イベント画像用（refile）
  attachment :group_image

  # 検索機能用
  def self.search_for(value)
    @groups = []
    @groups = Group.where(['name LIKE(?) OR introduction LIKE(?)', "%#{value}%", "%#{value}%"])
    @groups.uniq
  end

  # 通知機能(グループコメント)用
  def create_notification_comment!(current_user, group_comment)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    group = group_comment.group
    temp_ids = GroupComment.select(:user_id).where(group_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, group_comment.id, temp_id['user_id'])
      # 同時にグループ管理者に通知を送る
      if temp_id['user_id'] != group.admin_user_id
        save_notification_comment!(current_user, group_comment.id, group.admin_user_id)
      end
    end
  end

  def save_notification_comment!(current_user, group_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_group_notifications.new(
      group_id: id,
      group_comment_id: group_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.is_checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  # 通知機能(グループニュース)用
  def create_notification_news!(users, group)
    users.each do |user|
      # users（グループ所属のユーザー）に通知を送る
      notification = user.active_group_notifications.new(
        visiter_id: group.admin_user_id,
        visited_id: user.id,
        group_id: group.id,
        action: 'news'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :ensure_admin_user, only: %i[edit update] # 主催者以外はedit,updateできなくする

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.admin_user_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to group_path(@group), notice: 'グループ作成に成功しました'
    else
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @admin_user = User.find(@group.admin_user_id)
    @apply = Apply.find_by(group_id: @group.id, user_id: current_user.id)
    @group_news = GroupNew.where(group_id: @group.id).page(params[:page]).reverse_order.per(5)
    @group_comment = GroupComment.new
  end

  def index
    @groups = Group.all.page(params[:page]).reverse_order.per(10)
    @user = current_user # ユーザー情報表示用（サイドバー）
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to group_path, notice: '正常にイベント情報が変更されました。'
    else
      render 'edit'
    end
  end

  # 参加申請を許可すると、GroupUserレコードを生成し、該当のapplyレコードを削除する
  def join
    @group = Group.find(params[:group_id])
    @user = User.find(params[:user_id])
    @apply = Apply.find_by(params[:group_id], params[:user_id])
    @group.users << User.find(params[:user_id])
    @apply.destroy!
    flash[:notice] = '参加を承認しました。'
    @user.create_notification_approval!(@user, params[:group_id]) # models/user.rb参照：グループ参加申請と同時に通知作成
    redirect_to group_path(@group)
  end

  # 参加申請を却下すると、該当のapplyレコードを削除する
  def leave
    @apply = Apply.find_by(params[:group_id], params[:user_id])
    @apply.destroy!
    flash[:notice] = '申請を却下しました。。'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_admin_user
    @group = Group.find(params[:id])
    redirect_to group_path(@group) unless @group.admin_user_id == current_user.id
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_index.html.erb
<div class="col-12">
  <% groups.each do |group| %>
    <div class="card bg-light mb-2">
      <div class="row no-gutters">
        <div class="col-md-2 col-xs-1">
          <%= attachment_image_tag(group, :group_image, fallback: "no-image-icon.jpg", size: "100x100", class:"rounded-circle ml-2 mt-2" ) %>
        </div>
        <div class="col-10">
          <div class="card-body">
            <h5 class="card-title"><%= link_to group.name, group_path(group) %></h5>
            <p class="card-text"><%= group.introduction %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate groups %>
</div>

app/views/groups/edit.html.erb
<section id="group" class="bg-light">
  <%= render 'layouts/error', model: @group %>
  <div class="container">
    <div class ="row justify-content-center pt-3">
      <h1 class="col-12 text-center">グループ編集</h1>
      <div class="col-lg-6 col-sm-9">
        <%= form_with model:@group, local:true do |f| %>
          <div class="form-group">
            <%= f.label :グループ名 %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :グループ概要 %>
            <%= f.text_area :introduction, rows: 5, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :グループイメージ %>
            <%= f.attachment_field :group_image, class: "form-control-file event_image" %>
          </div>
          <div class="form-group text-center">
            <%= f.submit class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/groups/index.html.erb
<section id="group" class="bg-light">
  <div class="container">
    <div class='row'>
      <%= render 'users/user_info',user: @user %>
      <div class='col-lg-9 col-md-12 mt-3'>
        <div class="input-group form-inline">
          <h2 class="col-8">グループ一覧</h2>
          <%= form_with url:searches_group_path, method: :get, local: true do |f| %>
            <%= f.text_field "search[value]", placeholder: "グループ検索", class:"border-bottom form-control d-inline" %>
            <%= f.submit "検索", class:"btn btn-outline-secondary border-0 d-inline" %>
          <% end %>
        </div>
        <%= render 'groups/index',groups: @groups %>
      </div>
    </div>
  </div>
</group>

app/views/groups/new.html.erb
<section id="group" class="bg-light">
  <%= render 'layouts/error', model: @group %>
  <div class="container">
    <div class ="row justify-content-center">
      <h1 class="col-12 text-center mt-3">新規グループ作成</h1>
      <div class="col-lg-6 col-sm-9">
        <%= form_with model:@group, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name, 'グループ名*' %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction, 'グループ概要*' %>
            <%= f.text_area :introduction, rows: 5, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :グループイメージ %>
            <%= f.attachment_field :group_image, class: "form-control-file event_image" %>
          </div>
          <div class="form-group text-center">
            <%= f.submit class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/groups/show.html.erb
<section id="group" class="bg-light">
  <div class="container">
    <div class ="row">
      <h2 class="col-10 mt-3">
        グループ詳細
        <% if @apply %>
          <small>
            <i class="fas fa-exclamation-circle"></i>現在、このグループに参加申請中です。
          </small>
        <% end %>
      </h2>
      <table class="col-12 table table-striped table-condensed">
        <tr>
          <td class="col-3">
            <%= attachment_image_tag(@group, :group_image, fallback: "no-image-icon.jpg", size: "100x100", class:"rounded-circle" ) %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>グループ名</td>
          <td><%= @group.name %></td>
        </tr>
        <tr>
          <td>グループ概要</td>
          <td><%= @group.introduction %></td>
        </tr>
        <tr>
          <td>グループ主催者</td>
          <td><%= link_to @admin_user.name, user_path(@admin_user) %></td>
        </tr>
        <tr>
          <td>グループメンバー</td>
          <td>
            <% @group.users.each do |member| %>
              <li><%= link_to member.name, user_path(member) %><br></li>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="mx-auto">
        <% if @admin_user == current_user %>
          <%= link_to '編集する', edit_group_path, class: 'btn btn-info' %>
          <%= link_to "承認待ち一覧", group_applies_path(@group), class:"btn btn-primary" %>
        <% else %>
          <!-- ログインユーザが当該コミュニティに所属している場合 -->
          <% if @group.users.include?(current_user) %>
            <%= link_to '退会する', group_leave_path(@group), method: :delete, data:{ confirm: "「#{@group.name}」から退会します。よろしいですか？" } ,class:"btn btn-danger" %>
          <!-- 当該コミュニティには所属していないが、ログインはしている場合 -->
          <% elsif current_user %>
             <% if @apply %>
              <%= link_to '申請取消', group_apply_path(@group, apply_id: @apply.id), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= link_to '加入申請', group_applies_path(@group), method: :post, class: "btn btn-success" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="col-12">
        <h2>お知らせ</h2>
        <% @group_news.each do |group_new| %>
          <div class="card bg-light mb-2">
            <div class="card-body">
              <h5 class="card-title"><%= group_new.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= group_new.updated_at.strftime('%Y/%m/%d %H:%M') %></h6>
              <p class="card-text"><%= group_new.body %></p>
              <% if @admin_user == current_user %>
                <%= link_to '編集', edit_group_group_news_path(id: group_new.id, group_id: @group.id), class:"btn btn-info" %>
                <%= link_to '削除', group_group_news_path(id: group_new.id, group_id: @group.id), data: {confirm: "本当に削除してもよろしいですか？"}, method: :delete, class:"btn btn-danger" %>
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @group_news %>
        <div class="text-center">
          <% if @admin_user == current_user %>
            <%= link_to 'お知らせを投稿する', new_group_group_news_path(@group), class:"btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row col-12">
      <div id="group_comments" class="col-12">
        <%= render 'group_comments/index', group: @group %>
      </div>
    </div>
  </div>
</section>