config/routes.rb
Rails.application.routes.draw do
  # homes
  root to: 'homes#top'
  get 'homes/about'
  get 'homes/help'
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # user
  get '/confirm' => 'users#confirm', as: 'users_confirm'
  put '/users/:id/leave' => 'users#leave', as: 'users_leave'
  get '/users' => 'users#error' # hidden_field使用に伴うルーティングエラー用(新規登録)
  resources :users, only: %i[show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notices, only: [:index]
    delete '/notices/destroy_all' => 'notices#destroy_all'
  end
  # chat
  resources :chats, only: %i[show create]
  get '/chats' => 'chats#error' # hidden_field使用に伴うルーティングエラー用（チャット）
  # event
  patch 'events/:id/cancel' => 'events#cancel', as: 'cancel_event'
  resources :events, except: [:destroy] do
    get 'join' => 'events#join', as: 'join'
    delete 'leave' => 'events#leave', as: 'leave'
    resources :event_comments, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # group
  resources :groups, except: [:destroy] do
    get 'join' => 'groups#join', as: 'join'
    delete 'leave' => 'groups#leave', as: 'leave'
    resources :applies, only: %i[create destroy index]
    resources :group_news, only: %i[new create edit update destroy]
    resources :group_comments, only: %i[create destroy]
  end
  # search
  get 'searches/event' => 'searches#event'
  get 'searches/group' => 'searches#group'
  get 'searches/user' => 'searches#user'
  # tag
  resources :tags, only: [:show]
  # genre
  resources :genres, only: [:show]
  # contact
  resources :contacts, only: %i[new create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/user.rb
class User < ApplicationRecord
  # devise用
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  # バリデーション
  validates :name, length: { minimum: 1 , maximum: 20 } , uniqueness: true

  # アソシエーション
  # フォロー機能用：Relationship参照
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed # フォローしている場合→follower_idをフォローしている人
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower # フォローされている場合→followed_idをフォローしている人
  # DM機能用
  has_many :entries
  has_many :chats
  has_many :rooms, through: :user_rooms
  # イベント機能用
  has_many :event_users
  has_many :events, through: :event_users, dependent: :destroy
  # イベントコメント用
  has_many :event_comments, dependent: :destroy
  # イベントブックマーク用
  has_many :bookmarks, dependent: :destroy
  # グループ機能用
  has_many :group_users
  has_many :groups, through: :group_users
  # グループ承認機能用
  has_many :applies, dependent: :destroy
  has_many :groups, through: :applies
  # グループコメント機能用
  has_many :group_comments, dependent: :destroy
  # イベント通知機能用
  has_many :active_event_notifications, class_name: 'EventNotice', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_event_notifications, class_name: 'EventNotice', foreign_key: 'visited_id', dependent: :destroy
  # グループ通知機能用
  has_many :active_group_notifications, class_name: 'GroupNotice', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_group_notifications, class_name: 'GroupNotice', foreign_key: 'visited_id', dependent: :destroy

  # ユーザー画像用（refile）
  attachment :user_image

  # ユーザーが退会していない場合はtrue、退会している場合はfalseを返す。ログイン機能で退会済みユーザーを除外するため使用
  def active_for_authentication?
    super && (is_valid == true)
  end

  # フォローする時
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外す時
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか確認する場合
  def following?(user)
    followings.include?(user)
  end

  # 検索機能用
  def self.search_for(value)
    @users = []
    @users = User.where(['name LIKE(?) OR introduction LIKE(?)', "%#{value}%", "%#{value}%"])
    @users.uniq
  end

  # SNS認証用
  def self.find_or_create_for_oauth(auth)
    find_or_create_by!(email: auth.info.email) do |user|
      user.provider = auth.provider,
                      user.uid = auth.uid,
                      user.name = auth.info.name,
                      user.email = auth.info.email,
                      user.password = Devise.friendly_token[0, 20]
    end
  end

  # 通知機能用（フォローと同時に通知(EventNotice)を作成する）
  def create_notification_follow!(current_user)
    temp = EventNotice.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_event_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 通知機能用（イベント参加と同時に通知(EventNotice)を作成する）
  def create_notification_join!(current_user, event_id)
    temp = EventNotice.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'join'])
    if temp.blank?
      notification = current_user.active_event_notifications.new(
        visited_id: id,
        event_id: event_id,
        action: 'join'
      )
      notification.save if notification.valid?
    end
  end

  # 通知機能用（グループ参加申請と同時に通知(EventNotice)を作成する）
  def create_notification_apply!(current_user, group_id)
    temp = GroupNotice.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'join'])
    if temp.blank?
      notification = current_user.active_group_notifications.new(
        visited_id: id,
        group_id: group_id,
        action: 'apply'
      )
      notification.save if notification.valid?
    end
  end

  # 通知機能用（グループ参加承認と同時に通知(EventNotice)を作成する）
  def create_notification_approval!(current_user, group_id)
    temp = GroupNotice.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'approval'])
    if temp.blank?
      notification = current_user.active_group_notifications.new(
        visited_id: id,
        group_id: group_id,
        action: 'approval'
      )
      notification.save if notification.valid?
    end
  end

  # 通知機能用（チャット送信と同時に通知(EventNotice)を作成する）
  def create_notification_chat!(current_user, user_id)
    temp = EventNotice.where(['visiter_id = ? and visited_id = ? and action = ? ', current_user.id, user_id, 'chat'])
    if temp.blank?
      notification = current_user.active_event_notifications.new(
        visited_id: user_id.pop, # user_idにはチャット相手のidが格納されているが、配列になってしまっているため、.popで取り出し
        action: 'chat'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def google_oauth2
    callback_from(:google_oauth2)
  end

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_or_create_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  protected

  # 会員の論理削除のための記述。退会後は、同じメールアドレスではログイン不可とする。
  def reject_user
    # ログイン時に入力されたメールアドレスに対応するユーザーが存在するか探す
    email = params[:user][:email].downcase + '_is_deleted'
    @user = User.find_by(email: email)
    # emailを検索して該当があった場合
    if @user
      # 入力されたパスワードが正しく、かつactive_for_authentication?メソッドがfalseである（＝is_validがfalse：退会済み)場合
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = '退会済みです。再度ご登録をしてご利用ください。'
        redirect_to new_user_session_path
      else
        flash[:notice] = '項目を入力してください'
      end
    end
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:error]
  before_action :ensure_correct_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    user_events(@user) # コントローラー下部参照：ユーザーの関与しているイベントを抽出
    user_groups(@user) # コントローラー下部参照：ユーザーの関与しているグループを抽出
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = '登録情報を編集しました。'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  # 退会処理：ユーザーのis_validカラムをfalseに変更し、ログアウトさせる
  def leave
    @user = current_user
    @user.update(is_valid: false)
    deleted_email = @user.email + '_is_deleted' # 退会するユーザーのメールアドレスに「_is_deleted」を付ける（再登録時のユニーク制約回避）
    @user.update(email: deleted_email)
    @user.skip_email_changed_notification! # deviseによるアドレス変更時の確認メールを送る処理をスキップ
    reset_session
    redirect_to root_path
  end

  # 退会確認画面を表示
  def confirm; end

  # 新規登録画面で出るエラー対応用
  def error; end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
  end

  # ログインしているユーザーと編集しようとしているユーザーが一致しないと編集等をできなくする
  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

  # 参加前・参加済み・ブックマーク済のイベントを抽出（EventUserテーブルから検索）
  def user_events(user)
    @user_events = EventUser.where(user_id: user.id).pluck(:event_id).uniq
    @join_events = Event.where(id: @user_events).page(params[:page])
    @before_join_events = []
    @after_join_events = []
    @join_events.each do |event|
      # 参加前のイベントを抽出（EventUserテーブルから検索）
      if event.finish_at > DateTime.now
        @before_join_events << event
        @before_join_events = Kaminari.paginate_array(@before_join_events).page(params[:page]).per(5)
      # 参加済のイベントを抽出（EventUserテーブルから検索）
      else
        @after_join_events << event
        @after_join_events = Kaminari.paginate_array(@after_join_events).page(params[:page]).per(5)
      end
    end
    # ブックマークしたイベントを抽出
    @user_bookmarks = Bookmark.where(user_id: @user.id).pluck(:event_id).uniq
    @bookmark_events = Event.where(id: @user_bookmarks)
    @bookmark_events = @bookmark_events.page(params[:page]).per(5)
  end

  def user_groups(user)
    # 参加しているグループを抽出
    @user_groups = GroupUser.where(user_id: user.id).pluck(:group_id).uniq
    @join_groups = Group.where(id: @user_groups).page(params[:page]).per(5)
    # 参加申請中のグループを抽出
    @user_applies = Apply.where(user_id: user.id).pluck(:group_id).uniq
    @apply_groups = Group.where(id: @user_applies).page(params[:page]).per(5)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
			<th>イメージ</th>
		  <th>ユーザー名</th>
		  <th>プロフィール</th>
		  <th colspan="2"></th>
		</tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <% if user.is_valid == true %>
        <tr>
          <td><%= attachment_image_tag user, :user_image, format: 'jpeg', fallback: "no-image.jpg", size: "100x100", class:"rounded-circle ml-2 mt-2" %></td>
          <td><%= user.name %></td>
          <td><%= user.introduction %></td>
          <td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to 'フォローする', user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to '詳細', user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate users %>

app/views/users/_user_info.html.erb
<div class='col-md-12 col-lg-3 mt-3 border rounded bg-light mb-2 pb-3 h-100'>
  <table class='table'>
      <div class="text-center">
        <%= attachment_image_tag(user, :user_image, size: "200x200", fallback: "no-image.jpg", class:"rounded-circle mt-3 mb-3 img-responsive", alt: "ユーザーイメージ") %>
      </div>
    <tr>
  	  <th>ユーザー名</th>
  	  <th><%= user.name %></th>
    </tr>
    <tr>
      <th>フォロー中</th>
      <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
    </tr>
    <tr>
      <th>フォロワー</th>
      <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
    </tr>
  </table>
  <div class="accordion mb-2" id="accordionExample">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            プロフィール
          </button>
        </h5>
      </div>
      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
        <div class="card-body">
          <%= user.introduction %>
        </div>
      </div>
    </div>
  </div>
    <% if user == current_user %>
      <%= link_to 'ユーザー情報を編集する', edit_user_path(user), class: "col-12 btn btn-outline-secondary mb-1" %>
    <% end %>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォローを外す', user_relationships_path(user.id), method: :delete, class: "btn btn-primary col-12 mb-1" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class: "btn btn-success col-12 mb-1" %>
    <% end %>
  <% end %>
  <% if current_user != user %>
    <%= link_to 'メッセージを送る', chat_path(user.id), class: "btn btn-info col-12 mb-1" %>
  <% else %>
    <%= link_to 'イベントを作成する', new_event_path, class: "btn btn-info col-12 mb-1" %>
    <%= link_to 'グループを作成する', new_group_path, class: "btn btn-warning col-12 mb-1" %>
  <% end %>
</div>

app/views/users/confirm.html.erb
<section id="user" class="bg-light">
  <div class="container pt-5">
    <div class="text-center col-12">
      <div class="col-12">
        <h3 class="text-danger"><i class="fas fa-exclamation-triangle"></i>本当に退会しますか？<i class="fas fa-exclamation-triangle"></i></h3><br><br>
      </div>
      <div class="col-12">
        退会すると会員情報やこれまでのイベント参加履歴等が閲覧できなくなります。<br>
        ご注意ください。<br>
        退会する場合は,「退会する」をクリックしてください。<br><br>
      </div>
      <div class="col-12 pb-5">
        <%= link_to "退会しない", user_path(current_user), class: 'btn btn-primary' %>
        <%= link_to "退会する", users_leave_path(current_user), data: {confirm: "本当に退会してもよろしいですか？"}, method: :put, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section id="user" class="bg-light">
  <%= render 'layouts/error', model: @user %>
  <div class='container'>
    <div class='row pt-3'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2 class="col-12 text-center">ユーザー情報変更</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :ユーザー名 %>
            <%= f.text_field :name, class: "form-control name" %>
          </div>
          <div class="form-group">
            <%= f.label :ユーザー画像 %>
            <%= f.attachment_field :user_image, class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <%= f.label :プロフィール %>
            <%= f.text_area :introduction, rows: 5, class: "form-control introduction" %>
          </div>
          <div class="form-group text-center">
            <%= f.submit "変更", class: 'btn btn-secondary' %>
            <%= link_to '退会', users_confirm_path(current_user), class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/error.html.erb
<%= render 'layouts/header' %>
<section id="user" class="bg-light">
  <div class="container pt-5">
    <div class="text-center col-12">
      <div class="col-12">
        <h3 class="text-danger">リロードされたため、エラーが発生しました。</i></h3><br><br>
      </div>
      <div class="col-12">
        大変申し訳ございません、セッションが途切れたため、エラーが発生しました。<br>
        再度、以下のリンクから新規登録画面に移動してください。<br>
        <%= link_to "新規登録画面へ", new_user_registration_path %><br><br>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section id="user" class="bg-light">
  <div class="container">
    <div class='row'>
      <%= render 'user_info',user: @user %>
      <div class='col-lg-9 col-md-12 mt-3'>
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a href="#tab1" class="nav-link active" data-toggle="tab">イベント</a>
          </li>
          <li class="nav-item">
            <a href="#tab2" class="nav-link text-dark" data-toggle="tab">グループ</a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="tab1" class="tab-pane active">
            <h2 class="mt-2 border-bottom">参加予定のイベント一覧</h2>
            <% if @before_join_events.empty? %>
              <p>参加予定のイベントはありません。</p>
            <% else %>
              <div class="col-12 mt-2">
                <%= render 'events/index',events: @before_join_events %>
              </div>
            <% end %>
            <h2 class="mt-2 border-bottom">ブックマークしたイベント一覧</h2>
            <% if @bookmark_events.empty? %>
              <p>ブックマークしているイベントはありません。</p>
            <% else %>
              <div class="col-12 mt-2">
                <%= render 'events/index',events: @bookmark_events %>
              </div>
            <% end %>
            <h2 class="mt-2 border-bottom">過去に参加したイベント一覧</h2>
            <% if @after_join_events.empty? %>
              <p>過去に参加したイベントはありません。</p>
            <% else %>
              <div class="col-12 mt-2">
                <%= render 'events/index',events: @after_join_events %>
              </div>
            <% end %>
          </div>
          <div id="tab2" class="tab-pane">
            <h2 class="mt-2 border-bottom">所属しているグループ一覧</h2>
            <% if @join_groups.empty? %>
              <p>所属しているグループはありません。</p>
            <% else %>
              <div class="col-12 mt-2">
                <%= render 'groups/index',groups: @join_groups %>
              </div>
            <% end %>
            <h2 class="mt-2 border-bottom">参加申請中のグループ一覧</h2>
            <% if @apply_groups.empty? %>
              <p>参加申請中のグループはありません。</p>
            <% else %>
              <div class="col-12 mt-2">
                <%= render 'groups/index',groups: @apply_groups %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>