config/routes.rb
Rails.application.routes.draw do
  # homes
  root to: 'homes#top'
  get 'homes/about'
  get 'homes/help'
  # devise
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # user
  get '/confirm' => 'users#confirm', as: 'users_confirm'
  put '/users/:id/leave' => 'users#leave', as: 'users_leave'
  get '/users' => 'users#error' # hidden_field使用に伴うルーティングエラー用(新規登録)
  resources :users, only: %i[show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notices, only: [:index]
    delete '/notices/destroy_all' => 'notices#destroy_all'
  end
  # chat
  resources :chats, only: %i[show create]
  get '/chats' => 'chats#error' # hidden_field使用に伴うルーティングエラー用（チャット）
  # event
  patch 'events/:id/cancel' => 'events#cancel', as: 'cancel_event'
  resources :events, except: [:destroy] do
    get 'join' => 'events#join', as: 'join'
    delete 'leave' => 'events#leave', as: 'leave'
    resources :event_comments, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # group
  resources :groups, except: [:destroy] do
    get 'join' => 'groups#join', as: 'join'
    delete 'leave' => 'groups#leave', as: 'leave'
    resources :applies, only: %i[create destroy index]
    resources :group_news, only: %i[new create edit update destroy]
    resources :group_comments, only: %i[create destroy]
  end
  # search
  get 'searches/event' => 'searches#event'
  get 'searches/group' => 'searches#group'
  get 'searches/user' => 'searches#user'
  # tag
  resources :tags, only: [:show]
  # genre
  resources :genres, only: [:show]
  # contact
  resources :contacts, only: %i[new create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/event.rb
class Event < ApplicationRecord
  # バリデーション
  validates :name, length: { minimum: 1 , maximum: 50 }
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :start_at, presence: true
  validates :finish_at, presence: true
  validates :deadline, presence: true
  validate :after_now
  validate :after_start_at
  validate :before_start_at
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 2 }
  validates :tool, presence: true

  # 開始日時・終了日時・参加締切日時のいずれかが現在時刻より前になるとエラー
  def after_now
    if start_at < Time.current || finish_at < Time.current || deadline < Time.current
      errors.add(:base, '開始日時・終了日時・参加締切日時のいずれかが現在時刻より前になっています。')
    end
  end

  # 開始日時が終了日時より後になるとエラー
  def after_start_at
    errors.add(:base, '開始時刻が終了時刻より後になっています。') unless start_at < finish_at
  end

  # 参加締め切りが開始日時より後になるとエラー
  def before_start_at
    errors.add(:base, '開始時刻が参加締め切り時刻より前になっています。') unless start_at > deadline
  end

  # アソシエーション
  has_many :event_users
  has_many :users, through: :event_users, dependent: :destroy
  # ジャンル機能用
  belongs_to :genre
  # コメント機能用
  has_many :event_comments, dependent: :destroy
  # ブックマーク機能用
  has_many :bookmarks, dependent: :destroy
  # タグ機能用
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  # グループとの紐づけ用
  belongs_to :group, optional: true
  # 通知機能用
  has_many :event_notices, dependent: :destroy

  # イベント画像用（refile）
  attachment :event_image

  # simple_calender用のメソッド。start_timeが呼び出されると、start_atで設定した時刻が返る
  def start_time
    start_at
  end

  # ブックマーク確認用
  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  # 検索機能用：検索ワードでname,introductionカラムから検索
  def self.search_for(value)
    @events = []
    @events = Event.where(['name LIKE(?) OR introduction LIKE(?)', "%#{value}%", "%#{value}%"])
    @events.uniq
  end

  # タグ機能用：検索ワードでname,introductionカラムから検索
  def save_tag(sent_tags)
    current_tags = tags.pluck(:name) unless tags.nil? # events/createで保存した@eventに紐付いているタグが存在する場合、タグを配列で全て取得
    old_tags = current_tags - sent_tags # 現在取得した@eventに存在するタグから、送信されてきたタグを除いたタグをold_tagsとする
    new_tags = sent_tags - current_tags # 送信されてきたタグから、現在存在するタグを除いたタグをnew_tagsとする

    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end

    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(name: new)
      tags << new_tag
    end
  end

  # 通知機能(イベントコメント)用
  def create_notification_comment!(current_user, event_comment)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    event = event_comment.event
    temp_ids = EventComment.select(:user_id).where(event_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, event_comment_id, temp_id['user_id'])
      # 同時に、イベント管理者に通知を送る
      save_notification_comment!(current_user, event_comment.id, user_id) if temp_id['user_id'] != event.admin_user_id
    end
  end

  def save_notification_comment!(current_user, event_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_event_notifications.new(
      event_id: id,
      event_comment_id: event_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.is_checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :ensure_admin_user, only: %i[edit update cancel] # 主催者以外はedit,update,cancelできなくする

  def new
    @genres = Genre.all # ジャンル表示用
    @usergroups = GroupUser.where(user_id: current_user.id).pluck(:group_id) # ユーザーの所属するグループ表示するため、検索して@groupsへ
    @groups = Group.where(id: @usergroups)
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin_user_id = current_user.id
    @event.users << current_user
    tag_list = params[:event][:tag_name].split(nil) # タグ機能用
    if @event.save
      @event.save_tag(tag_list)
      redirect_to event_path(@event), notice: 'イベント作成に成功しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @admin_user = User.find(@event.admin_user_id)
    @event_comment = EventComment.new
    @event_tags = @event.tags # タグ機能用：現在選択されているイベントに紐づいているタグを入手
    @event_group = Group.find_by(id: @event.group_id) # グループイベント表示用：現在選択されているイベントに紐づいているグループを入手
    @group_users = GroupUser.where(user_id: current_user.id).pluck(:group_id) # ユーザーの所属するグループ表示するため、検索して@user_groupsへ
    @user_groups = Group.where(id: @group_users)
  end

  def index
    @calender_events = Event.all # カレンダー表示用
    @events = Event.all.page(params[:page]).reverse_order.per(10)
    @user = current_user # ユーザー情報表示用（サイドバー）
    @genres = Genre.all # ジャンル一覧表示用
    @tags = Tag.all # タグ一覧表示用
  end

  def edit
    @event = Event.find(params[:id])
    @usergroups = GroupUser.where(user_id: current_user.id).pluck(:group_id) # ユーザーの所属するグループ表示するため、検索して@groupsへ
    @groups = Group.where(id: @usergroups)
    @tags = @event.tags.pluck(:name) # イベントに紐づいたタグの名前のみ抽出
    @event_tags = @tags.join(' ') # 抽出したタグ名を半角スペースで結合
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      tag_list = params[:event][:tag_name].split(' ') # 入力されたタグを受け取る
      update_tags(tag_list, @event) # コントローラー下部参照
      redirect_to event_path(@event), notice: '正常にイベント情報が変更されました。'
    else
      render 'edit'
    end
  end

  # イベントの開催を中止または中止から再開する処理
  def cancel
    @event = Event.find(params[:id])
    # イベントが開催中の場合
    if @event.is_valid == true
      if @event.update(is_valid: false)
        flash[:notice] = 'イベントを中止しました。イベント詳細ページから再開も可能です。'
      else
        render 'show'
      end
    # イベントが中止中の場合
    else
      @event.update(is_valid: true)
      flash[:notice] = 'イベントを再開しました。'
    end
    @admin_user = User.find(@event.admin_user_id)
    redirect_to event_path(@event)
  end

  # イベントに参加する際の処理
  def join
    @event = Event.find(params[:event_id])
    @event.users << current_user
    @user = User.find(@event.admin_user_id)
    @user.create_notification_join!(current_user, params[:event_id]) # models/user.rb参照：イベント参加と同時に通知作成
    redirect_to event_path(@event)
  end

  # イベント参加を中止する際の処理
  def leave
    @event = Event.find(params[:event_id])
    @event.users.delete(current_user)
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:name, :introduction, :genre_id, :start_at, :finish_at, :deadline, :tool,
                                  :event_image, :capacity, :group_id)
  end

  def ensure_admin_user
    @event = Event.find(params[:id])
    redirect_to event_path(@event) unless @event.admin_user_id == current_user.id
  end

  # タグの更新処理
  def update_tags(tag_list, event)
    @old_tagmaps = Tagmap.where(event_id: event.id) # 編集しようとしているイベントに紐づいていた中間テーブルを@old_tagmapsに入れる
    # この時点で一旦中間テーブルのデータを削除
    @old_tagmaps.each do |map|
      map.delete
    end
    # tagの更新
    tag_list.each do |tag_name|
      @tag = Tag.find_or_create_by(name: tag_name) # タグを入力された内容で探し、あればそのまま、なければ新規作成
      @tag.save
      # 再度1個づつ中間テーブルへ登録
      new_tagmap = Tagmap.new(event_id: @event.id, tag_id: @tag.id)
      new_tagmap.save
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  # イベントの開催日時と終了日時を結合
  def event_time(event)
    "#{event.start_at.strftime('%Y/%m/%d %H:%M')} ~ #{event.finish_at.strftime('%Y/%m/%d %H:%M')}"
  end
end

app/views/events/_calender.html.erb
<h3>イベントカレンダー</h3>
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to event.name, event_path(event) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/_index.html.erb
<div class="col-12">
  <% events.each do |event| %>
    <div class="card bg-light mb-2">
      <div class="row no-gutters">
        <% if event.is_valid == true %>
          <div class="col-md-2 col-xs-1">
            <%= attachment_image_tag(event, :event_image, fallback: "no-image-icon.jpg", size: "100x100", class:"rounded-circle ml-2 mt-2" ) %>
          </div>
          <div class="col-10">
            <div class="card-body">
              <h5 class="card-title"><%= link_to event.name, event_path(event) %></h5>
              <p class="card-text"><%= event.introduction %></p>
              <td><%= event_time(event) %></td>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= paginate events %>
</div>

app/views/events/edit.html.erb
<section id="event" class="bg-light">
  <%= render 'layouts/error', model: @event %>
  <div class="container">
    <div class ="row justify-content-center pt-3">
      <h1 class="col-12 text-center">イベント編集</h1>
      <div class="col-lg-6 col-sm-9">
        <%= form_with model:@event, local:true do |f| %>
          <div class="form-group">
            <%= f.label :イベント名 %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :イベント概要 %>
            <%= f.text_area :introduction, rows: 3, class: "form-control" %>
          </div>
          <div class="form-select">
            <%= f.label :ジャンル選択 %>
            <%= f.collection_select( :genre_id, Genre.all, :id, :name, {} ,{:class => "form-control"}) %>
          </div>
          <div class="form-group">
            <%= f.label :開始日時 %>
            <%= f.datetime_field :start_at, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :終了日時 %>
            <%= f.datetime_field :finish_at, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :参加締切日時 %>
            <%= f.datetime_field :deadline, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :参加定員 %>
            <%= f.text_field :capacity, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :使用ツール（オフラインの場合は開催場所を記載して下さい） %>
            <%= f.text_field :tool, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :タグ（半角スペースで区切るで複数のタグを付けることができます。） %>
            <%= f.text_field :tag_name, class: "form-control", value: @tags %>
          </div>
          <div class="form-group">
            <%= f.label :イベントイメージ %>
            <%= f.attachment_field :event_image, class: "form-control-file event_image" %>
          </div>
          <% if @groups %>
            <div class="form-group">
              <%= f.label :グループ（選択すると該当グループメンバーのみが参加できます）  %>
              <%= f.collection_select( :group_id, @groups.all, :id, :name, { include_blank: 'グループなし'} ,{:class => "form-control"}) %>
            </div>
          <% end %>
          <div class="form-group text-center">
            <%= f.submit '編集する',class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section id="event" class="bg-light">
  <div class="container">
    <div class='row'>
      <%= render 'users/user_info',user: @user %>
      <div class='col-lg-9 col-md-12 mt-3'>
        <div class="input-group form-inline">
          <h2 class="col-8">イベント一覧</h2>
          <%= form_with url:searches_event_path, method: :get, local: true do |f| %>
            <%= f.text_field "search[value]", placeholder: "イベント検索", class:"border-bottom form-control d-inline" %>
            <%= f.submit "検索", class:"btn btn-outline-secondary border-0 d-inline" %>
          <% end %>
        </div>
        <ul class="nav nav-tabs">
          <li class="nav-item">
              <a href="#tab1" class="nav-link active" data-toggle="tab">カレンダー</a>
          </li>
          <li class="nav-item">
              <a href="#tab2" class="nav-link" data-toggle="tab">一覧</a>
          </li>
          <li class="nav-item">
              <a href="#tab3" class="nav-link" data-toggle="tab">ジャンル</a>
          </li>
          <li class="nav-item">
              <a href="#tab4" class="nav-link" data-toggle="tab">タグ</a>
          </li>
        </ul>
        <div class="tab-content">
          <div id="tab1" class="tab-pane active">
            <%= render 'events/calender',events: @calender_events %>
          <div id="tab2" class="tab-pane">
            <div class="col-12 mt-2">
              <%= render 'events/index',events: @events %>
            </div>
          </div>
          <div id="tab3" class="tab-pane">
            <div class="col-12 mt-2">
              <%= render 'genres/index',genres: @genres %>
            </div>
          </div>
          <div id="tab4" class="tab-pane">
            <div class="col-12 mt-2">
              <%= render 'tags/index',tags: @tags %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<section id="event" class="bg-light">
  <%= render 'layouts/error', model: @event %>
  <div class="container">
    <div class ="row justify-content-center">
      <h1 class="col-12 text-center mt-3">新規イベント作成</h1>
      <div class="col-lg-6 col-sm-9">
        <%= form_with model:@event, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name, 'イベント名*' %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction, 'イベント概要*' %>
            <%= f.text_area :introduction, rows: 3, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :genre_id, 'ジャンル*' %>
            <%= f.collection_select( :genre_id, Genre.all, :id, :name, {} ,{:class => "form-control"}) %>
          </div>
          <div class="form-group">
            <%= f.label :start_at, '開始日時*' %>
            <%= f.datetime_field :start_at, class: "form-control", value: Time.current.strftime('%Y-%m-%dT00:00:00') %>
          </div>
          <div class="form-group">
            <%= f.label :finish_at, '終了日時*' %>
            <%= f.datetime_field :finish_at, class: "form-control", value: Time.current.strftime('%Y-%m-%dT00:00:00') %>
          </div>
          <div class="form-group">
            <%= f.label :deadline, '参加締切日時*' %>
            <%= f.datetime_field :deadline, class: "form-control", value: Time.current.strftime('%Y-%m-%dT00:00:00') %>
          </div>
          <div class="form-group">
            <%= f.label :capacity, '参加人数定員*' %>
            <%= f.text_field :capacity, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :tool, '使用ツール*（オフラインの場合は開催場所を記載して下さい）' %>
            <%= f.text_field :tool, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :イベントイメージ %>
            <%= f.attachment_field :event_image, class: "form-control-file event_image" %>
          </div>
          <div class="form-group">
            <%= f.label :タグ（半角スペースで区切るで複数のタグを付けることができます。） %>
            <%= f.text_field :tag_name, class: "form-control" %>
          </div>
          <% if @groups %>
            <div class="form-group">
              <%= f.label :グループ（選択すると該当グループメンバーのみが閲覧できます）  %>
              <%= f.collection_select( :group_id, @groups.all, :id, :name, { include_blank: 'グループなし'} ,{:class => "form-control"}) %>
            </div>
          <% end %>
          <div class="form-group text-center">
            <%= f.submit class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<section id="event" class="bg-light">
  <%= render 'layouts/error', model: @event %>
  <div class="container">
    <div class ="row pt-3">
      <h2 class="col-11">
        イベント詳細
        <small>
          <% if @event.deadline < Time.now %>
            <i class="fas fa-exclamation-circle"></i>このイベントはすでに参加が締め切られています。
          <% elsif @event.is_valid == false %>
            <i class="fas fa-exclamation-circle"></i>このイベントの開催は中止されています。
          <% elsif @event.users.count >= @event.capacity %>
            <i class="fas fa-exclamation-circle"></i>このイベントはすでに定員に達しています。
          <% elsif @event.users.include?(current_user) %>
            <i class="fas fa-exclamation-circle"></i>このイベントに参加予定です。
          <% end %>
        </small>
      </h2>
      <h4 class="text-right col-1" id="bookmark">
        <%= render 'bookmarks/bookmark', event: @event %>
      </h4>
      <table class="col-12 table table-striped table-condensed">
        <tr>
          <td>
            <%= attachment_image_tag(@event, :event_image, fallback: "no-image-icon.jpg", size: "100x100", class:"rounded-circle" ) %>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>イベント名</td>
          <td><%= @event.name %></td>
        </tr>
        <tr>
          <td>イベント概要</td>
          <td><%= @event.introduction %></td>
        </tr>
        <tr>
          <td>開催日時</td>
          <td><%= event_time(@event) %></td>
        </tr>
        <tr>
          <td>参加締め切り日時</td>
          <td><%= @event.deadline.strftime('%Y/%m/%d %H:%M') %></td>
        </tr>
        <tr>
          <td>参加定員</td>
          <td><%= @event.capacity %>人(現在<%= @event.users.count %>人が参加中)</td>
        </tr>
        <tr>
          <td>使用ツール</td>
          <td><%= @event.tool %></td>
        </tr>
        <tr>
          <td>タグ</td>
          <td>
            <% @event_tags.each do |tag| %>
              <li class="btn btn-dark"><%= link_to tag.name, tag_path(tag.id), class:"text-white" %></li>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>イベント主催者</td>
          <td><%= link_to @admin_user.name, user_path(@admin_user) %></td>
        </tr>
        <% if @admin_user == current_user %>
          <tr>
            <td>イベント参加者</td>
            <td>
              <% @event.users.each do |member| %>
                <li><%= link_to member.name, user_path(member) %><br></li>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% if @event_group %>
          <tr>
            <td>グループ</td>
            <td>このイベントは<%= link_to @event_group.name, group_path(@event_group) %>のメンバーのみ参加できます。</td>
            </td>
          </tr>
        <% end %>
      </table>
      <div class="mx-auto">
        <% if user_signed_in? %>
          <% if @admin_user == current_user %>
            <%= link_to '編集する', edit_event_path, class: 'btn btn-info' %>
            <% if @event.is_valid == true %>
              <%= link_to '中止する', cancel_event_path, class: 'btn btn-danger', method: :patch %>
            <% else %>
              <%= link_to '再開する', cancel_event_path, class: 'btn btn-success', method: :patch %>
            <% end %>
          <% else %>
            <% if @event.users.include?(current_user) %>
              <%= link_to '参加を取り消す', event_leave_path(@event), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <% unless @event.deadline < Time.now || @event.is_valid == false || @event.users.count >= @event.capacity %>
                <% if @user_groups.include?(@event_group) %>
                  参加するには、<%= link_to @event_group.name, group_path(@event_group) %>に参加してください。
                <% else %>
                  <%= link_to '参加する', event_join_path(@event), class: 'btn btn-success'%>
                <% end %>
              <% else %>
                <p><i class="fas fa-exclamation-circle"></i>このイベントには参加できません。</p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <%#コメント機能呼び出し%>
      <div id="event_comments" class="col-12">
        <%= render 'event_comments/index', event: @event %>
      </div>
    </div>
  </div>
</section>